### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kaspesla** [TheoPierne/spot-sdk-js#3]
Something not quite right here. I had to comment out some of this to get it to go.

```
(base) ken@lll spot-sdk-js % node examples/hello_spot/hello_spot.js --username spot --password my password -v 192.168.80.3
/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:208
  [power_pb.FanPowerCommandResponse.Status.STATUS_OK]: [null, null],
                                    ^

TypeError: Cannot read properties of undefined (reading 'Status')
    at Object.<anonymous> (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:208:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/command_line.js:42:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
(base) ken@lll spot-sdk-js % node examples/hello_spot/hello_spot.js --username spot --password spotspotspot -v 192.168.80.3
/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:208
  [power_pb.FanPowerCommandResponse.Status.STATUS_OK]: [null, null],
                                    ^
```

**Comment by TheoPierne** [comment]
I commited a new version of proto files, which includes the status for FanPowerCommandResponse

-  https://github.com/TheoPierne/spot-sdk-js/commit/e3131ab3fe645704ac2ba9cb81887198dca5e2c0

This issue should be resolved !
