### ISSUE TITLE
OverriddenError

### ISSUE THREAD

**Issue by kaspesla** [TheoPierne/spot-sdk-js#4]
After commenting out the Fan error lines, I'm failing here.

```[2022-11-02 18:09:49] [debug] [HelloSpotClient]: [COMMON] response: /bosdyn.api.PowerService/PowerCommandFeedback 
{"header":{"requestHeader":{"requestTimestamp":{"seconds":1667426989,"nanos":332000000},"clientName":"HelloSpotClientlll.local:sdk.js-34067","disableRpcLogging":false},"requestReceivedTimestamp":{"seconds":1667427281,"nanos":626245679},"responseTimestamp":{"seconds":1667427281,"nanos":726378827},"error":{"code":1,"message":""},"request":{"typeUrl":"type.googleapis.com/bosdyn.api.PowerCommandFeedbackRequest","value":"CjUKDAit1YubBhCA1qeeARIlSGVsbG9TcG90Q2xpZW50bGxsLmxvY2FsOnNkay5qcy0zNDA2NxAE"}},"status":11,"blockingFaultsList":[]}
 
OverriddenError: The command was overridden and is no longer valid.
    at _power_command (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:491:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async power_on_motors (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:313:3)
    at async power_on (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:291:3)
    at async Robot.power_on (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/robot.js:456:5)
    at async hello_spot (/Users/ken/Sandbox/spot-sdk-js/examples/hello_spot/hello_spot.js:40:5)
    at async main (/Users/ken/Sandbox/spot-sdk-js/examples/hello_spot/hello_spot.js:129:3) {
  response: null
}
```

**Comment by kaspesla** [comment]
I went in and ignored this error, and now I get this:

```

0
[2022-11-02 18:28:21] [debug] [HelloSpotClient]: [COMMON] blocking request: /bosdyn.api.PowerService/PowerCommandFeedback 
{"header":{"requestTimestamp":{"seconds":1667428101,"nanos":487000064},"clientName":"HelloSpotClientlll.local:sdk.js-34316","disableRpcLogging":false},"powerCommandId":9}
 
[2022-11-02 18:28:21] [debug] [HelloSpotClient]: [COMMON] response: /bosdyn.api.PowerService/PowerCommandFeedback 
{"header":{"requestHeader":{"requestTimestamp":{"seconds":1667428101,"nanos":487000064},"clientName":"HelloSpotClientlll.local:sdk.js-34316","disableRpcLogging":false},"requestReceivedTimestamp":{"seconds":1667428393,"nanos":788760716},"responseTimestamp":{"seconds":1667428393,"nanos":888884050},"error":{"code":1,"message":""},"request":{"typeUrl":"type.googleapis.com/bosdyn.api.PowerCommandFeedbackRequest","value":"CjUKDAiF3oubBhCAkJzoARIlSGVsbG9TcG90Q2xpZW50bGxsLmxvY2FsOnNkay5qcy0zNDMxNhAJ"}},"status":11,"blockingFaultsList":[]}
 
0
[2022-11-02 18:28:21] [debug] [HelloSpotClient]: [COMMON] blocking request: /bosdyn.api.PowerService/PowerCommandFeedback 
{"header":{"requestTimestamp":{"seconds":1667428101,"nanos":607000064},"clientName":"HelloSpotClientlll.local:sdk.js-34316","disableRpcLogging":false},"powerCommandId":9}
 
Pensez à retirer le log du catch
Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Object.callErrorFromStatus (/Users/ken/Sandbox/spot-sdk-js/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/ken/Sandbox/spot-sdk-js/node_modules/@grpc/grpc-js/build/src/client.js:195:52)
    at Object.onReceiveStatus (/Users/ken/Sandbox/spot-sdk-js/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/Users/ken/Sandbox/spot-sdk-js/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/ken/Sandbox/spot-sdk-js/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/ken/Sandbox/spot-sdk-js/node_modules/@grpc/grpc-js/build/src/client.js:163:34)
    at ServiceClientImpl.powerCommandFeedback (/Users/ken/Sandbox/spot-sdk-js/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:276:9
    at new Promise (<anonymous>)
    at PowerClient.#make (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:273:12)
    at PowerClient.call (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:327:34)
    at PowerClient.power_command_feedback (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:114:17)
    at _power_command (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:483:43)
    at async power_on_motors (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:313:3)
    at async power_on (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:291:3) {
  code: 4,
  details: 'Deadline exceeded',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
TimedOutError: Deadline exceeded
    at translate_exception (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/channel.js:165:12)
    at PowerClient.call (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:336:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _power_command (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:483:24)
    at async power_on_motors (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:313:3)
    at async power_on (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/power.js:291:3)
    at async Robot.power_on (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/robot.js:456:5)
    at async hello_spot (/Users/ken/Sandbox/spot-sdk-js/examples/hello_spot/hello_spot.js:40:5)
    at async main (/Users/ken/Sandbox/spot-sdk-js/examples/hello_spot/hello_spot.js:129:3)
[2022-11-02 18:28:21] [debug] [HelloSpotClient]: [COMMON] blocking request: /bosdyn.api.LeaseService/ReturnLease 
{"header":{"requestTimestamp":{"seconds":1667428101,"nanos":698999808},"clientName":"HelloSpotClientlll.local:sdk.js-34316","disableRpcLogging":false},"lease":{"resource":"body","epoch":"wHLMIritQzbspCPf","sequenceList":[16],"clientNamesList":["root"]}}
 
[2022-11-02 18:28:21] [debug] [HelloSpotClient]: [COMMON] response: /bosdyn.api.LeaseService/ReturnLease 
{"header":{"requestHeader":{"requestTimestamp":{"seconds":1667428101,"nanos":698999808},"clientName":"HelloSpotClientlll.local:sdk.js-34316","disableRpcLogging":false},"requestReceivedTimestamp":{"seconds":1667428394,"nanos":4963317},"responseTimestamp":{"seconds":1667428394,"nanos":4992163},"error":{"code":1,"message":""},"request":{"typeUrl":"type.googleapis.com/bosdyn.api.ReturnLeaseRequest","value":"CjUKDAiF3oubBhCAyKfNAhIlSGVsbG9TcG90Q2xpZW50bGxsLmxvY2FsOnNkay5qcy0zNDMxNhIhCgRib2R5EhB3SExNSXJpdFF6YnNwQ1BmGgEQIgRyb290"}},"status":3}
 
oui time sync
oui token
/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:108
    return new error_type(response, message);
           ^

NotActiveLeaseError
    at error_factory (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:108:12)
    at _handle_return_errors (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/lease.js:463:12)
    at LeaseClient.handle_response (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:350:48)
    at LeaseClient.call (/Users/ken/Sandbox/spot-sdk-js/bosdyn-client/common.js:345:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async hello_spot (/Users/ken/Sandbox/spot-sdk-js/examples/hello_spot/hello_spot.js:80:5)
    at async main (/Users/ken/Sandbox/spot-sdk-js/examples/hello_spot/hello_spot.js:129:3) {
  response: {
    header: {
      requestHeader: {
        requestTimestamp: { seconds: 1667428101, nanos: 698999808 },
        clientName: 'HelloSpotClientlll.local:sdk.js-34316',
        disableRpcLogging: false
      },
      requestReceivedTimestamp: { seconds: 1667428394, nanos: 4963317 },
      responseTimestamp: { seconds: 1667428394, nanos: 4992163 },
      error: { code: 1, message: '', data: undefined },
      request: {
        typeUrl: 'type.googleapis.com/bosdyn.api.ReturnLeaseRequest',
        value: 'CjUKDAiF3oubBhCAyKfNAhIlSGVsbG9TcG90Q2xpZW50bGxsLmxvY2FsOnNkay5qcy0zNDMxNhIhCgRib2R5EhB3SExNSXJpdFF6YnNwQ1BmGgEQIgRyb290'
      }
    },
    status: 3
  }
}
```

**Comment by TheoPierne** [comment]
Sorry to take so long, I have a lot of work at the moment but I started working on a fix, but I can't tell you when it will be released!
